package com.sergius.core.presentation.designsystem.theme

import androidx.compose.ui.graphics.Color

val TaskyLightBackground = Color(0xFF16161C)
val TaskyLightPrimary = Color(0xFF16161C)
val TaskyLightOnPrimary = Color(0xFFFFFFFF)
val TaskyLightOnBackground = Color(0xFFFFFFFF)
val TaskyLightSurface = Color(0xFFFFFFFF)
val TaskyLightOnSurface = Color(0xFF3A4045)
val TaskyLightOnSurfaceHigh = Color(0xFFF2F3F7)
val TaskyLightOnSurfaceVariant = Color(0xFF76808F)
val TaskyLightLink = Color(0xFF8E97FD)
val TaskyCheckIconColor = Color(0xFF279F70)
val TaskyCalendarSupplementary = Color(0xFFFDEFA8)

val TaskyDarkBackground = Color(0xFF16161C)
val TaskyDarkPrimary = Color(0xFFFFFFFF)
val TaskyDarkOnPrimary = Color(0xFF16161C)
val TaskyDarkOnBackground = Color(0xFFFFFFFF)
val TaskyDarkSurface = Color(0xFF1B1B20)
val TaskyDarkOnSurface = Color(0xFFF2F3F7)
val TaskyDarkOnSurfaceHigh = Color(0xFF242428)
val TaskyDarkOnSurfaceVariant = Color(0xFF808B9B)

val TaskyGreen = Color(0xFF52B28D)
val TaskyLightGreen = Color(0xFFCAEF45)
val TaskyDarkGreen = Color(0xFF258E66)
val TaskyDarkGreen10 = Color(0xFF34A579)
val TaskyYellow = Color(0xFFFDEFA8)
val TaskyRed = Color(0xFFF34B51)
val TaskyDarkRed = Color(0xFFF88084)
val TaskyLightGrey = Color(0xFF9FA7B1)
val TaskyDarkGrey = Color(0xFF656C79)
val TaskyLightPurple = Color(0xFF8E97FD)
val TaskyDarkPurple = Color(0xFFB1B8FE)